### ISSUE TITLE
Better ReadMe adding Table of Contents such as About,Features, Installation, Contributing, License

### ISSUE THREAD

**Issue by Roshr2211** [GameSphere-MultiPlayer/Community-Page#12] opened 2024-05-10 14:31 UTC
### Describe the bug ✍️

ReadMe shows the steps to create PR and doesn't describe the project.

### Provide step by step information reproduce the bug 📄

We can add Table of Contents such as About , Features, Installation, Contributing, License in. Snippets of community page will be added in ReadMe to enhance readability. Please assign this ask to me . I am a GSSOC-24 contributor

### Select program in which you are contributing

GSSOC-24

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINE]() of this project.

**Comment by Durgesh4993** [comment] 2024-05-10 14:38
@Roshr2211 I think so we have added proper detail how a contributor send a PR. Contributing, License and CodeofCoduct. If you have any better approach you can explain

**Comment by Durgesh4993** [comment] 2024-05-10 14:38
If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Roshr2211** [comment] 2024-05-10 15:55
The PR has been made. Please let me know if there are any changes to be made.

**Comment by Durgesh4993** [comment] 2024-05-11 21:18
@Roshr2211 Don't send PR untill the issue is not assigned you

**Comment by Durgesh4993** [comment] 2024-05-11 21:21
I'll appreciate your learning spirit, but this PR is waste because the Table of Content is already provide by GitHub

**Comment by Durgesh4993** [comment] 2024-05-11 21:23
If you have any doubt you can directly as on our discord (https://discord.gg/rZb46cCMmK), we have created seprate chennals for all projects...

Thank you :)

**Comment by Durgesh4993** [comment] 2024-05-11 21:23
I am closing this issue for now

**Closed by Durgesh4993** 2024-05-11 21:23 UTC
